### ISSUE TITLE
web确定的图和数据图

### ISSUE THREAD

**Issue by Vanderah** [hack4gz/2015.gzhack.io#11]
![web data](https://cloud.githubusercontent.com/assets/9332220/7568934/2f8cae06-f838-11e4-86d4-6940be967ab5.jpg)
![web pic](https://cloud.githubusercontent.com/assets/9332220/7568935/2f8cf050-f838-11e4-8f25-1b8e0caca0e5.jpg)

ps：
1.标题那里可以滑动的3个图只做了2个
2.Who we are 那里每个人的照片待收集
2.赞助商那块的图标等我去切

**Comment by Vanderah** [comment]
@allenfantasy

**Comment by Vanderah** [comment]
![Uploading [1].jpg…]()
![Uploading [1]-2.jpg…]()

**Comment by Vanderah** [comment]
![1 -1](https://cloud.githubusercontent.com/assets/9332220/7569298/6b1f389c-f83a-11e4-93bd-3be9fde4cc71.jpg)
![1 -2](https://cloud.githubusercontent.com/assets/9332220/7569299/6b20908e-f83a-11e4-878f-c3819c540435.jpg)

**Comment by allenfantasy** [comment]
@Vanderah 
- "开源项目进展" 那里需要一个红色的带广州格子地图的背景图；
- "Who we are" 需要各种头像
- 需要列出来的各种图标的固定大小版
- 有些地方的字体大小不大对（在 iMac 的大屏幕上应该可以，但是换成笔记本电脑看感觉不对），需要找个时间面对面的调一下

**Comment by Vanderah** [comment]
1 我明天去公司切图
2 我催一下老大
3 指的是赞助商那块的logo吗？切成几块大图还是一个一个单独切下来
4 ok，还是用比例给吧

**Comment by Vanderah** [comment]
@allenfantasy （不好意思忘了at

**Comment by allenfantasy** [comment]
@Vanderah 我先把其他地方搞定吧。赞助商那边的 logo 按分类做成几个大图就可以了

**Comment by Vanderah** [comment]
@allenfantasy ok

**Comment by Vanderah** [comment]
@allenfantasy 赞助商那整块是之前在gzhack.io上拿的，后来有更新，到更新完了再出一版图
![gz map](https://cloud.githubusercontent.com/assets/9332220/7670478/e7478ada-fcd8-11e4-8925-39c1f75e58e5.png)
![default](https://cloud.githubusercontent.com/assets/9332220/7670479/ef35a57e-fcd8-11e4-80d6-eb21b6d06403.jpg)
![default](https://cloud.githubusercontent.com/assets/9332220/7670480/f2edac66-fcd8-11e4-8d17-817c9d1306ee.png)
![default](https://cloud.githubusercontent.com/assets/9332220/7670482/018fe694-fcd9-11e4-805d-de7b35db2ac3.png)

**Comment by Vanderah** [comment]
![default](https://cloud.githubusercontent.com/assets/9332220/7670501/ae3f49de-fcd9-11e4-86f9-5267b822bfb3.png)

**Comment by Vanderah** [comment]
@allenfantasy 小版字体已标亮黄色，其他间距之类的直接除以1.5
![data](https://cloud.githubusercontent.com/assets/9332220/7670584/ab50b0f2-fcdc-11e4-80bc-eebea2b8c621.jpg)

**Comment by Vanderah** [comment]
@allenfantasy 
![row1](https://cloud.githubusercontent.com/assets/9332220/7677080/b92d3be2-fd7b-11e4-906b-e2a73b541acc.png)

**Comment by Vanderah** [comment]
@allenfantasy 
（图upload不上去）需要实现的效果：
所有用黑色半透明蒙版遮盖，鼠标挪上去的时候该照片上的遮盖消失，出现名字和自我介绍框

照片上面的自我介绍框：
1 文字框背景色#584f4f，透明度0.6，180x90px
文字框下端带一个三角形，三角形下端稍覆盖照片
2 文本div宽140px，上下左右居中
3 font：14px（小屏幕大屏幕都一样），白色，黑体，行高16px

照片下面的名字：
背景：黑色，透明度0.5，100x18px
font 14px，白色

**Comment by Vanderah** [comment]
文案：
嘉豪【总打杂，没人写代码的时候写代码，没人写文案的时候写文案，没人拉口条的时候拉口条】
嘉雯【首席文案君，曾在颜值APP中获得918万/1000万的高分并引（dao）以（chu）为（xuan）豪（yao）】
蛋哥【没有跆拳道黑带的门将不是好程序员】
小黑【脸大到总是挡住wifi信号的呆萌设计尸】
鑫磊【搬砖的，据老大说是除了他之外颜值最高的，不服来打我脸啊】
张帆 Mercy【主要技能宣传排版写文案，偶尔脑洞大开干点“不切实际”的事，喜欢和具有生命力的人一起工作】
罗丹【打杂小二一个，和那个雕塑家没半毛钱关系(沉思状...)】
Cheman【一枚感性创业的小六】
大力【笔耕不辍练出了肌肉 方便日后扛相机的 大力】

**Comment by allenfantasy** [comment]
@Vanderah 样式已经部署到 [官网](http://gzhack.io/) 关于照片墙的内容我新开了一个 issue #14
