### ISSUE TITLE
照片墙

### ISSUE THREAD

**Issue by allenfantasy** [hack4gz/2015.gzhack.io#14]
### 需要实现的效果

所有用黑色半透明蒙版遮盖，鼠标挪上去的时候该照片上的遮盖消失，出现名字和自我介绍框

照片上面的自我介绍框：
1 文字框背景色#584f4f，透明度0.6，180x90px
文字框下端带一个三角形，三角形下端稍覆盖照片
2 文本div宽140px，上下左右居中
3 font：14px（小屏幕大屏幕都一样），白色，黑体，行高16px

照片下面的名字：
背景：黑色，透明度0.5，100x18px
font 14px，白色
### 图

![](https://cloud.githubusercontent.com/assets/9332220/7677080/b92d3be2-fd7b-11e4-906b-e2a73b541acc.png)
### 文案

嘉豪【总打杂，没人写代码的时候写代码，没人写文案的时候写文案，没人拉口条的时候拉口条】
嘉雯【首席文案君，曾在颜值APP中获得918万/1000万的高分并引（dao）以（chu）为（xuan）豪（yao）】
蛋哥【没有跆拳道黑带的门将不是好程序员】
小黑【脸大到总是挡住wifi信号的呆萌设计尸】
鑫磊【搬砖的，据老大说是除了他之外颜值最高的，不服来打我脸啊】
张帆 Mercy【主要技能宣传排版写文案，偶尔脑洞大开干点“不切实际”的事，喜欢和具有生命力的人一起工作】
罗丹【打杂小二一个，和那个雕塑家没半毛钱关系(沉思状...)】
Cheman【一枚感性创业的小六】
大力【笔耕不辍练出了肌肉 方便日后扛相机的 大力】

**Comment by allenfantasy** [comment]
@Vanderah 求更新大家的头像图。我做完别的任务就来上这个

【IMPORTANT】能否给我一份含有黑白阴影和彩色的头像大图，包含所有人的头像小图？表示现在只有彩色图片无力做黑白效果……

**Comment by Martin91** [comment]
Finished, see https://github.com/gzhack/gzhack-site/pull/17
