### ISSUE TITLE
web需要修改的地方

### ISSUE THREAD

**Issue by Vanderah** [hack4gz/2015.gzhack.io#15]
- [x] 首页图被压扁了
- [x] 报名button的字缩小
- [x] button做成跟neuron一样的效果（鼠标挪上去变成只有边框的button
- [x] header上的报名做成一个style的button
- [x] header的高度缩短20px
- [x] header在web向下滑动的时候顶在最上面，不要消失
- [x] 加上照片墙
- [x] 在赞助商下面加“媒体合作伙伴”
- [x] 最后一part加链接

**Comment by Vanderah** [comment]
@allenfantasy

**Comment by Vanderah** [comment]
@allenfantasy 
![default](https://cloud.githubusercontent.com/assets/9332220/7744503/77de5c18-ffd6-11e4-8891-5cf55129f7aa.png)
大小、位置和开放数据合作伙伴的规格一样

**Comment by allenfantasy** [comment]
@Vanderah 照片墙我单独放在 #14 了，我先搞定其他的先~

**Comment by Vanderah** [comment]
@allenfantasy 蛋哥换一下赞助商那些的图片（社区合作伙伴是一行8个，现在有9个，请改到8个）——
![default](https://cloud.githubusercontent.com/assets/9332220/7769968/a74b4106-00bb-11e5-9a76-1e317617974d.png)
![default](https://cloud.githubusercontent.com/assets/9332220/7769904/04ed445e-00bb-11e5-8154-860d982af5c8.png)
![new](https://cloud.githubusercontent.com/assets/9332220/7769910/09a55d88-00bb-11e5-9943-a74f3f5dfe7e.png)

**Comment by Vanderah** [comment]
1 大屏的电脑首页图片还是一样问题：压缩、第一页下面被遮挡
2 鼠标悬停在首页图上，图还是会自动滑动变化
3 社区合作伙伴最后下面边界留白160px

**Comment by Vanderah** [comment]
@allenfantasy 
PS：首页图片被压缩，但是网页自动放久，不知道什么时候图片就会自己变正常，不清楚原因

细节调整：
1  Who We Are 模块标题和正文：font-weight: 300;
2 开源项目进展标题下面的英文：font-size: 22px;  letter-spacing: 0.06em;
3 Who we are 和 开源项目进展 模块：margin-bottom: 5em;
4 常见问题 回答正文：font-size:20px;
5 赞助那块：标题 font-size:27px;

**Comment by Vanderah** [comment]
6 赞助那块：标题 color: #9E9E9E;

**Comment by Vanderah** [comment]
@allenfantasy 

首页图片的style修改：
首页图片原本只有一层，现在分成2层：
①底图：无字无灰色蒙版data背景图【位置固定，不随着页面下滑而下滑】【暂空】

②中图：下沿的城市剪影png【会随页面下滑，像一块玻璃一样可以看见背景的相对移动；但不会左右滑动】（图大小和原先div一样）
![div](https://cloud.githubusercontent.com/assets/9332220/7771195/27b78438-00c8-11e5-8ced-d91bad25fd59.png)

③顶图：（新加了第三张图）有信息内容的三张png【随网页上下滑动；自动左右切换】（图大小和原先div一样）
![1](https://cloud.githubusercontent.com/assets/9332220/7771192/27b4d35a-00c8-11e5-83aa-9cc6e0b2154b.png)
![2](https://cloud.githubusercontent.com/assets/9332220/7771194/27b74d60-00c8-11e5-85e9-d1983b57c81e.png)
![3](https://cloud.githubusercontent.com/assets/9332220/7771193/27b50442-00c8-11e5-8868-2ffbea944e1d.png)

**Comment by allenfantasy** [comment]
这两天真心是没有时间做这个了。。。 @Martin91 @chenbin92 请求支援！！！！

**Comment by allenfantasy** [comment]
@Vanderah 如果是这种新的需求。。就开个新的 issue 吧（if there's next time

**Comment by Martin91** [comment]
@Vanderah 这里提到的问题我都创建了新的 issues 跟进，所以暂时先关闭这个 issue ，如果新的 issues 有疏漏的，麻烦补充！
