### ISSUE TITLE
更换承办方、赞助商、媒体合作伙伴的图

### ISSUE THREAD

**Issue by Vanderah** [hack4gz/2015.gzhack.io#25]
@Martin91 @allenfantasy 

承办方：
![default](https://cloud.githubusercontent.com/assets/9332220/7788021/ecdf2eb6-025b-11e5-97b1-365026c8da70.png)

媒体合作伙伴：
![default](https://cloud.githubusercontent.com/assets/9332220/7788020/e7b63bd2-025b-11e5-8648-d9155db98fa1.png)

**Comment by Vanderah** [comment]
新的媒体合作伙伴：
![default](https://cloud.githubusercontent.com/assets/9332220/7793680/cdb3675c-02f4-11e5-87f8-4c0849ffea23.png)

**Comment by Vanderah** [comment]
@Martin91  @allenfantasy  @chenbin92 
（记得承办方也要换上面那张新的）
媒体合作伙伴最新：
![default](https://cloud.githubusercontent.com/assets/9332220/7815507/653f6592-03fb-11e5-8b21-4c87d68a0966.png)
社区合作伙伴最新：
![default](https://cloud.githubusercontent.com/assets/9332220/7815514/726d6728-03fb-11e5-9b8f-58216a941a46.png)

**Comment by Vanderah** [comment]
现在的logo放置好像是左对齐的，某些屏幕尺寸下右边留白比左边多很多，请整体居中对齐

**Comment by allenfantasy** [comment]
@Vanderah 已更新部署
