### ISSUE TITLE
照片墙

### ISSUE THREAD

**Issue by Vanderah** [hack4gz/2015.gzhack.io#27]
@allenfantasy @Martin91 

只有这么多现在，不要重复放，以后有的话再继续添加
![new row](https://cloud.githubusercontent.com/assets/9332220/7788194/3eb05686-0264-11e5-92a6-6859e81ed53e.png)

1-9已经有具体的介绍，下面是从第10个开始：

Martin：Ruby工程师，常出没于各类线下技术社区
阿八：2.5次元光怪陆离爱问为什么星人。就是只打杂样样行励志成为游戏王的女人~
郭海旋：小菜鸟，要默默的farm
章以迪：坚决听命外联小组长的指挥，仗着英文还行专门负责勾搭外国友人寻求合作机会
尼克菌：什么都要试一试结果最后死于食物中毒。不不不我不是神农谢谢
Yolo：爱动漫和小说的骨灰级宅
Zed：请不要叫我程序猿，我不是修电脑的。我的使命是改变世界！请跟紧我的脚步，来，先搬了这堆砖！
busyzhong：来自中大，学渣一枚；没智商，有技； 好吃，懒做；睡，玩。
青芽：技术组酱油党一枚。本科即将毕业但最近仍在学校附近迷路，对此感到无限自卑中
Tony Han：基本上技能点就剩写代码了，顺带跟产品经理吵吵架什么的
Jackie Xia：想做社会主义螺丝钉然而并没有什么卵用的宣传部员

**Comment by Vanderah** [comment]
![image](https://cloud.githubusercontent.com/assets/9332220/7788223/c37bbbd0-0264-11e5-90dd-5cfae4876a65.png)
照片墙名字这里请往下挪一点（可能是1px或2px，保持上下留空一样多）

**Comment by allenfantasy** [comment]
hhhh 我是来吐槽“并没有什么卵用”这句话的…… 

ps. 编辑修改了介绍里的 typo

**Comment by Vanderah** [comment]
@allenfantasy @Martin91 @chenbin92 

照片基本就这么多，每张照片大小从100px改到80px，照片间距从10px改到8px，每行还是9张
![all-pic_2280x80](https://cloud.githubusercontent.com/assets/9332220/7813867/d689faec-03f0-11e5-822d-0ecdec743729.png)

 从第22个开始的介绍：
高佬：中意行下巷仔影下相 ，开左间“士多”卖啲无用既嘢，企图从精神层面捍卫城市最基本既特质
周老师：精神上的90后，专业媒体人&摄影师，主要任务是设计灯布和印海报
王二狗：策划。日常是读书睡觉写文案，然而参加这个活动我一个代码都不会打
辉浩：嘿，你个diao毛！
唐毅俊 ：然而这并没有什么卵用

**Comment by Martin91** [comment]
@Vanderah 已经修复部署，麻烦检查！
