### ISSUE TITLE
首页图片被压缩问题

### ISSUE THREAD

**Issue by Vanderah** [hack4gz/2015.gzhack.io#34]
问题描述：
大屏尺寸下，网页刚打开的时候首页图片呈被压缩状态：
![image](https://cloud.githubusercontent.com/assets/9332220/7827879/fe16065a-045e-11e5-8ae0-8ae9a8d9f41e.png)
右键审查元素，或者拉小屏幕再放大的时候图片会恢复正常

**Comment by Vanderah** [comment]
@allenfantasy @Martin91 @chenbin92

**Comment by Martin91** [comment]
@allenfantasy 是不是考虑用 media query 会更好？我看代码里边你是基于 js 计算宽度之类的？

**Comment by allenfantasy** [comment]
@Martin91 对，这个地方没写好。我来 take over 吧

**Comment by allenfantasy** [comment]
@Martin91 用 media query 的问题是不能维持住原来图片的长宽比，基于 js 做的原因就是这个。

小黑报的那个 bug 是因为我一开始调整大小时有个地方写错了。修复之后就可以了
