### ISSUE TITLE
【照片墙】新的照片加入

### ISSUE THREAD

**Issue by Vanderah** [hack4gz/2015.gzhack.io#35]
@allenfantasy  @Martin91  @chenbin92 

![new row](https://cloud.githubusercontent.com/assets/9332220/7828106/b9ec5760-0461-11e5-8e3d-7498e46b35a4.png)

最后那张照片：
Bruce：前端开发

**Comment by allenfantasy** [comment]
@chenbin92 亲修改个自我介绍吧

**Comment by Vanderah** [comment]
@allenfantasy 

好吧……又多了一张……
请每行放10张照片，and用代码每张缩小到70px，谢谢orz
![new row](https://cloud.githubusercontent.com/assets/9332220/7832333/d5f1a54e-0490-11e5-8334-cecfa33aeb5b.png)

许晓雯:除了产品设计什么都懂一点点的产品菜鸟兼业余PR

**Comment by Martin91** [comment]
马婷继续认领任务！

**Comment by Vanderah** [comment]
马婷师兄 goodjob！

**Comment by Martin91** [comment]
@Vanderah 记得检查。
