### ISSUE TITLE
首页图片滑动问题

### ISSUE THREAD

**Issue by Vanderah** [hack4gz/2015.gzhack.io#36]
@allenfantasy  @Martin91  @chenbin92 
现在的问题：
设定程序是鼠标放在图片上图片就不会滚动，
但是因为首页图片很大，几乎占满了整个页面，
打开页面时鼠标有95%的概率是放在首页图片上的。
也就等于95%的用户刚打开网页时，如果不自己点击翻页，
是看不到后面两张图的。

所以：
要么，鼠标放在上面图片也会滑动，只有专门点某个点的时候才会keep住；
要么，刚打开网页的时候，就算鼠标放在图片上，图片也会滑动，但是之后的操作是鼠标放在上面网页不会滑动。

and，我觉得有必要在图片左右加向左向右的大箭头

**Comment by allenfantasy** [comment]
能否和 @Mr-Wiredancer （老大）讨论一下？涉及 UX 的部分审慎一下稍好。

实现的话没有问题~

**Comment by Vanderah** [comment]
@Mr-Wiredancer 老大你怎么看

**Comment by Martin91** [comment]
@Vanderah @allenfantasy @Mr-Wiredancer 现在这个问题是还没有结论吗

**Comment by allenfantasy** [comment]
这个 issue 我觉得如果 **有人做的话可以做** ，老大太忙了估计没时间来看这个细节了。

归纳下小黑的意见：
1. 鼠标悬停在 slider 上时，slider 仍会自动滑动
2. 设置两边的箭头方便访问者切换 slider （现在的点太小了）

**Comment by allenfantasy** [comment]
@Martin91 @Justin-lu 有空帮个忙做这个？

**Comment by Justin-lu** [comment]
@allenfantasy 没问题。

**Comment by Justin-lu** [comment]
@allenfantasy 总结小黑的意见：
我现在的实现是：
1. 停止自动轮播
2. 添加左右箭头

**Comment by allenfantasy** [comment]
> 我现在的实现是：
> 1. 停止自动轮播

@Justin-lu 现在是效果是鼠标在 slider 上时也有自动轮播吧？

**Comment by Martin91** [comment]
@allenfantasy 我把 Justin 的代码改掉了，他的实现是停止了自动轮播，我把代码改回自动轮播，并且不会因为鼠标在上边而停止自动轮播。

**Comment by allenfantasy** [comment]
@Martin91 恩 那就没问题啦，现在的效果挺好的。

不过那个箭头的颜色现在是蓝色，感觉不大对，稍微改成浅灰可能更好
