### ISSUE TITLE
手机端适应的问题

### ISSUE THREAD

**Issue by Vanderah** [hack4gz/2015.gzhack.io#38]
@Martin91  @chenbin92  @allenfantasy 
![wechat_1432736676](https://cloud.githubusercontent.com/assets/9332220/7838407/53b83848-04bf-11e5-9f61-56eb4fc6e8a4.jpeg)
1 图片被拉长了
2 照片墙那里的CSS代码不work

![wechat_1432736817](https://cloud.githubusercontent.com/assets/9332220/7838442/825e9a3e-04bf-11e5-8753-d80ad8f9810e.jpeg)
F&A 地点这块的文字排版有问题

**Comment by Martin91** [comment]
@Vanderah @allenfantasy 照片墙的问题我已经在 #42 里边修复了，现在就是另外两个问题没处理。

**Comment by allenfantasy** [comment]
@Vanderah 用的是 iphone 上的 Safari 么？

在以下手机浏览器测试没有出现这个问题：
- 红米 - 微信浏览器
- 红米 - Chrome

**Comment by tony612** [comment]
这个目测是 `calc(100% - 700px);` 导致的

**Comment by Vanderah** [comment]
@allenfantasy  @Martin91  @tony612 
iPhone的微信自带浏览器以及UC浏览器
在地图文字这里都有问题
图片墙可以正常工作

**Comment by chaucerling** [comment]
地点的文字在 Opera 上显示也是有问题
