### ISSUE TITLE
用新的 Slider 实现

### ISSUE THREAD

**Issue by allenfantasy** [hack4gz/2015.gzhack.io#39]
http://www.idangero.us/swiper/#.VWXc-5Oqqko

**Comment by tony612** [comment]
我来改吧，之前比较忙，都没能提交代码。。 :sweat_smile: 如果你们还没有开始做这个的话

**Comment by Martin91** [comment]
@tony612 那应该就你来咯

**Comment by tony612** [comment]
@Martin91 不过说实话，现在前端做的比较少，希望不会太久。。

**Comment by Martin91** [comment]
@tony612 没事，刚好给你练手，多好的机会，再不行我们再上。
