### ISSUE TITLE
[WIP]更换赞助商和媒体合作伙伴图片

### ISSUE THREAD

**Issue by Vanderah** [hack4gz/2015.gzhack.io#45]
@Martin91  @tony612  @allenfantasy 
赞助商：
![default](https://cloud.githubusercontent.com/assets/9332220/7860551/9ec5ce32-057c-11e5-88c1-3f80d295cc3e.png)
（BearyChat网址：https://bearychat.com/ ）
媒体合作伙伴：
![default](https://cloud.githubusercontent.com/assets/9332220/7860569/c31fc030-057c-11e5-8f21-c83c3cb543dc.png)
（TechNode网址：http://technode.com/ ）

**Comment by tony612** [comment]
![2015_ ___hack_for_gz](https://cloud.githubusercontent.com/assets/1253659/7861996/dab0ea90-0585-11e5-8d05-513d7e9e5a52.png)
@Vanderah 这效果行不？

**Comment by Vanderah** [comment]
@tony612 
媒体合作伙伴放一行就好，请不要过行

**Comment by Vanderah** [comment]
超算广州的链接请改成新标签页打开，现在是原页跳转

**Comment by tony612** [comment]
@Vanderah Got it

**Comment by tony612** [comment]
![2015_ ___hack_for_gz](https://cloud.githubusercontent.com/assets/1253659/7884927/96c658c8-0653-11e5-9907-3f8dc87295bb.png)
@Vanderah 这样呢？ 因为这行都比较长，所以有点挤。。。

**Comment by Vanderah** [comment]
@tony612 
Tony，请问你用的是多宽的屏幕？
因为在我这边电脑，空间还剩挺多的
你预一行最多到1600px，如果屏幕小于1600的宽就自动适应换行，如果大于1600，放进去应该是没有问题的才对
![-2](https://cloud.githubusercontent.com/assets/9332220/7885252/602b96e6-0655-11e5-8ade-3c87f4291bb6.jpg)

**Comment by Vanderah** [comment]
@tony612 如果还是有问题请问一下 @allenfantasy  @Martin91 
我觉得应该不需要顶这么死的才对……

**Comment by tony612** [comment]
@Vanderah 13寸的。。 1280px

**Comment by tony612** [comment]
![2015_ ___hack_for_gz](https://cloud.githubusercontent.com/assets/1253659/7886116/75287190-065a-11e5-802e-9c2d2b0bd1da.png)
我的是这样。。

**Comment by Martin91** [comment]
@Vanderah 还是要尽量考虑 1280 左右尺寸的，毕竟很多人都是用笔记本访问的，一般13寸-15寸的笔记本屏幕宽度是 1280、1366、1440 px 。1920 px 应该是23寸外置显示屏的吧。

**Comment by Vanderah** [comment]
原来是这样……不好意思因为我用的两台电脑都是大屏的orz……
我们来拟定一个自适应的尺寸吧！
比如小于1440px的屏幕可以用：
左右各留空80px，满了自动过行
社区合作伙伴 宽150px
其它伙伴 宽200px

**Comment by Vanderah** [comment]
可以慢点更这块，因为有一些信息换了，还在等logo
【先马给自己看的，不要管我：
（在最前面）指导单位：番禺区人民政府
主办单位：国家数字家庭应用示范产业基地番禺区服务委员会办公室 广州大学城管理委员会 
承办单位：原来的不变，加上广东星海数字家庭产业技术研究院有限公司

**Comment by Martin91** [comment]
@Vanderah 这些内容确定了吗？

**Comment by allenfantasy** [comment]
@Martin91 这个不急，等最终确认了再 update 不迟

**Comment by Vanderah** [comment]
@Martin91 @allenfantasy 
![logo](https://cloud.githubusercontent.com/assets/9332220/7977605/b96ad3a8-0abe-11e5-8fe2-12a3b052be85.png)

1.为了方便统一的格式，我把最新的所有logo都排在这张png里面了
格式：除了超算中心是400px，每个logo都是宽200px，高100px，logo之间没有间距

2.在“主办方”类上面加一个“指导单位”，内容：广州市番禺区人民政府；font size：28px
“主办方”改成“主办单位”，内容：广州市番禺区科技工业商务和信息化局（过行）广州市大学城管理委员会；font size：28px
“承办方”改成“承办单位”，内容：国家数字家庭应用示范产业基地番禺区服务委员会办公室（font size：28px）（过行）前四个logo
赞助商：第5（占了400px的超算）、6个logo——共2个
媒体合作伙伴：第7-12个logo——共6个【位置调整，注意网页链接顺序调整】
开放数据合作：第13-15个logo——共3个
社区合作伙伴：剩下的——共14个【社区合作伙伴之前有的13个位置都没有改变，最后多加了坊间的】
