### ISSUE TITLE
更个照片墙orz

### ISSUE THREAD

**Issue by Vanderah** [hack4gz/2015.gzhack.io#50]
@Martin91  @allenfantasy  @tony612 
![new row](https://cloud.githubusercontent.com/assets/9332220/7911356/6f1da66c-088f-11e5-9101-c2843079c958.png)

最后那张：
小杜：会点代码的产品经理

**Comment by tony612** [comment]
周老师那个图现在去掉了么？

**Comment by tony612** [comment]
找到了，好像还没。。
