### ISSUE TITLE
啦啦啦，照片墙geng'x更新=。。=

### ISSUE THREAD

**Issue by Vanderah** [hack4gz/2015.gzhack.io#52]
@allenfantasy  没有找到Justin的账号能at他（挥手
![new row](https://cloud.githubusercontent.com/assets/9332220/7928475/5dc399a0-0923-11e5-88e4-af0b652fa3f4.png)

Justin：不会修电脑的程序员

**Comment by allenfantasy** [comment]
@Justin-lu （这样就可以了

**Comment by Justin-lu** [comment]
@allenfantasy 我没权限push代码。

**Comment by Martin91** [comment]
@Justin-lu 已经邀请你成为成员，麻烦确认。

**Comment by Justin-lu** [comment]
@Martin91 

> remote: Permission to gzhack/gzhack-site.git denied to Justin-lu.
> fatal: unable to access 'https://github.com/gzhack/gzhack-site.git/': The requested URL returned error: 403
