### ISSUE TITLE
改到6月5日的图

### ISSUE THREAD

**Issue by Vanderah** [hack4gz/2015.gzhack.io#7]
![Uploading 6月5日图.jpg…]()

**Comment by Vanderah** [comment]
@allenfantasy

**Comment by Vanderah** [comment]
![6 5](https://cloud.githubusercontent.com/assets/9332220/7488234/d9542c72-f3f9-11e4-8f4c-68e9a8278c67.jpg)

**Comment by allenfantasy** [comment]
图已经加进 repo 了
